### ISSUE TITLE
hello, I want to pruning LSTM neuron but I got some problem

### ISSUE THREAD

**Issue by jacksonly** [BenWhetton/keras-surgeon#1]
model = delete_channels(model, model.layers[0], [1], copy=True)
ValueError: This layer has not got any channels.

**Comment by BenWhetton** [comment]
Hi there,
Sorry for the late response. If you would still like to try this, feel free to supply some example code and I will try to work out what's going on. At a glance, it looks like you might be trying to prune the `Input` layer which has no neurons.
