### ISSUE TITLE
Python 2 compatibility broken

### ISSUE THREAD

**Issue by kartynnik** [BenWhetton/keras-surgeon#12]
With this line at least:
https://github.com/BenWhetton/keras-surgeon/blob/0cb919e49faf3ba120763a4a253ce63a32bbbe95/src/kerassurgeon/surgeon.py#L54
...although the PyPI package is not Python 3-only.

**Comment by BenWhetton** [comment]
Unfortunately, I missed the python_requires=">=3" from the setup.py file in the very first release so pip seems to install v0.0.1 on python 2.

Now, the python version is specfied as 3 or above in the setup.py file. 
It is also clearly stated in the readme in the Limitations section that only python 3 is supported.

Do you happen to know of any way around this except deleting the first release from pypi? Is there a good reason why I shouldn't delete the first release now?

**Comment by BenWhetton** [comment]
Deleted the old release so it cannot be pip installed on Python 2.
