### ISSUE TITLE
Error in the readme file.kindly change it

### ISSUE THREAD

**Issue by anujshah1003** [BenWhetton/keras-surgeon#26]
surgeon.add_job('delete_channels', model, layer_1, channels=[2, 6, 8])
surgeon.add_job('insert_layer', model, layer_2, new_layer=new_layer_1)

it should be 
surgeon.add_job('delete_channels',layer_1, channels=[2, 6, 8])
surgeon.add_job('insert_layer', layer_2, new_layer=new_layer_1)

**Comment by BenWhetton** [comment]
Done in 4176dae224c51a29c3884dc251548cce4fcf14d4
