### ISSUE TITLE
Freeze keras version

### ISSUE THREAD

**Issue by arsenyinfo** [BenWhetton/keras-surgeon#3]
Hello, 
Thanks for the tool. 

Would you please specify the version of `keras` required for the library? It didn't work at my machine, and it looks like some keras API has changed.

**Comment by BenWhetton** [comment]
Hi there,
Thanks for raising this issue. I have a bit more time now so I hope to be more responsive in future. The latest release (0.1.0) on PyPI should work with all released versions of `keras` >= 2.0.7.
