### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by Sangkwun** [BenWhetton/keras-surgeon#6]
I used same method in example for prune to my Inceptionv3 model.
It consumes too much memory for get_model_apoz.
So I wan to know your hardware spec for iris sample.

**Comment by BenWhetton** [comment]
Hi there,
I am using a Geforce 1060 6GB graphics card
At what point do you run out of memory?

**Comment by Sangkwun** [comment]
First time, I tested it in AWS EC2 P2.xlarge instance which has 11GB GPU memory. I found memory issue so Now I'm testing with tensorflow cpu version with RAM for memory storage. It consumes more than 20GB for calculating APOZ...

conv2d_1
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-10-905f5054d807> in <module>()
     13 while percent_pruned <= total_percent_pruning:
     14     # Prune the model
---> 15     apoz_df = get_model_apoz(model, validation_generator)
     16     percent_pruned += percent_pruning
     17     print('pruning up to ', str(percent_pruned),

<ipython-input-8-1be66b3b14c5> in get_model_apoz(model, generator)
     33             print(layer.name)
     34             apoz.extend([(layer.name, i, value) for (i, value)
---> 35                          in enumerate(get_apoz(model, layer, generator))])
     36 
     37     layer_name, index, apoz_value = zip(*apoz)

~/.local/share/virtualenvs/pruning-bMmaF54q/lib/python3.6/site-packages/kerassurgeon/identify.py in get_apoz(model, layer, x_val, node_indices)
     61             temp_model = Model(model.inputs, act_layer.get_output_at(act_index))
     62             a = temp_model.predict_generator(
---> 63                     x_val, x_val.n // x_val.batch_size)
     64         else:
     65             get_activations = k.function(

~/.local/share/virtualenvs/pruning-bMmaF54q/lib/python3.6/site-packages/keras/legacy/interfaces.py in wrapper(*args, **kwargs)
     89                 warnings.warn('Update your `' + object_name +
     90                               '` call to the Keras 2 API: ' + signature, stacklevel=2)
---> 91             return func(*args, **kwargs)
     92         wrapper._original_function = func
     93         return wrapper

~/.local/share/virtualenvs/pruning-bMmaF54q/lib/python3.6/site-packages/keras/engine/training.py in predict_generator(self, generator, steps, max_queue_size, workers, use_multiprocessing, verbose)
   1528             workers=workers,
   1529             use_multiprocessing=use_multiprocessing,
-> 1530             verbose=verbose)

~/.local/share/virtualenvs/pruning-bMmaF54q/lib/python3.6/site-packages/keras/engine/training_generator.py in predict_generator(model, generator, steps, max_queue_size, workers, use_multiprocessing, verbose)
    455             return all_outs[0][0]
    456         else:
--> 457             return np.concatenate(all_outs[0])
    458     if steps_done == 1:
    459         return [out[0] for out in all_outs]

MemoryError: 

This is error when i run it in Instance. I changed batch size to minimize memory usage, It makes better but still slow and needs lots memories.

**Comment by hammadsaeed** [comment]
Did you figure this out?

**Comment by BenWhetton** [comment]
Are you encountering this problem with the example from the repo or your own code? I can't really help if it's your code unless you put it up here to review. The example uses a batch size of 16 and it works fine on my geforce 1060 6GB.

I have made a small change in 0.1.1 which should improve the memory consumption a bit but I woudn't expect it to make a huge difference. Bear in mind that if you calculate the APOZ for every channel in the model, it must store those values in memory somewhere.

I have previously encountered problems with increasing amounts of memory being consumed when iteratively pruning. This was solved by deleting the model and resetting tensorflow between iterations:
https://github.com/BenWhetton/keras-surgeon/blob/0cb919e49faf3ba120763a4a253ce63a32bbbe95/src/kerassurgeon/examples/inception_flowers_prune.py#L108-L112

I don't know if the problem still exists with the latest versions of tensorflow but it's worth trying if you haven't already.

**Comment by prshnthrv** [comment]
I am having the same trouble. Even though I reduce the batch size to 4, the script freezes in get_model_apoz() in the first iteration. Anyone figured out why?

**Comment by BenWhetton** [comment]
Could you please tell me your versions of:
- Python (2 is not supported)
- Tensorflow (gpu or cpu?)
- Keras
- Kerassurgeon (make sure its the latest version)

I'll see if I can reproduce your problem with the same setup.

What is your hardware configuration out of interest?

**Comment by prshnthrv** [comment]
Hi, I am using Python 3.5. Tensorflow GPU 1.9.0, Keras 2.1.6. I just pulled kerassurgeon latest.
I have Titan X GPU. 
I am able to run the lenet example you have shared, where it doesn't use the batch generator. However, when I am trying to prune my network with a batchgenerator similar to what is there in the inception_flowers example you have, it just runs out of memory.

Thank you for such a quick response and appreciate your help!

**Comment by prshnthrv** [comment]
I think I was able to figure out the issue. When using a databatchgenerator, in the get_apoz function you have check to detect if a generator is passed to the function:

if isinstance(x_val, Iterator):
    temp_model = Model(model.inputs, act_layer.get_output_at(act_index))
    a = temp_model.predict_generator(
    x_val, x_val.n // x_val.batch_size)
else:
     get_activations = k.function(
     [utils.single_element(model.inputs), k.learning_phase()],
     [act_layer.get_output_at(act_index)])
     a = get_activations([x_val, 0])[0]

However, that condition is not true even though a generator is passed, so it is executing the else part and it gets into an infinite loop where it is just reading data.

**Comment by BenWhetton** [comment]
Thanks for looking into this! I think you're right. There seem to be two image Iterator classes at:
- `keras_preprocessing.image.iterator`
- `keras.preprocessing.image.iterator`

I'll have a new release out with a more generic check asap.

On the other hand, the traceback provided by @Sangkwun higher up suggests that the code took the correct path at that point in his case:
> ~/.local/share/virtualenvs/pruning-bMmaF54q/lib/python3.6/site-packages/kerassurgeon/identify.py in get_apoz(model, layer, x_val, node_indices)
> 61 temp_model = Model(model.inputs, act_layer.get_output_at(act_index))
> 62 a = temp_model.predict_generator(
> ---> 63 x_val, x_val.n // x_val.batch_size)
> 64 else:
> 65 get_activations = k.function(

However, I guess the `predict_generator` call might use *a lot* of memory if the dataset is large and the layer has a large number of outputs because it will calculate the outputs of the layer for every input image. I can probably work something out to fix that but it might still take some time to run.

There is probably a trade-off to work out regarding how big the pruning dataset should be.

**Comment by BenWhetton** [comment]
Version 0.1.3 which was just released should fix the "infinite loop" repeatable bug. There are definitely opportunities to improve the memory usage but I don't think this ticket needs to stay open for that.

**Comment by prshnthrv** [comment]
Hi Ben, Thanks for your prompt response and the quick fix.

**Comment by nheelam** [comment]
> Hi Ben, Thanks for your prompt response and the quick fix.

Hi, May I know whether did you still face the same problem?
