### ISSUE TITLE
channel pruning

### ISSUE THREAD

**Issue by ycxia** [BenWhetton/keras-surgeon#7]
Thank you for your repository!
your channel pruning method need to set the index, I think the method [https://github.com/yihui-he/channel-pruning](url) is better. but this repository is implenmented usingCaffe, can you implenment it using tensorflow or keras? thank you!

**Comment by BenWhetton** [comment]
Hi there!

The main purpose of this package is to facilitate deleting channels/neurons in keras (by specifiying the index as you correctly pointed out). I have included a simple method for identifying which channels to delete based on the average percentage of zero activations in the `identify.py` module.

I don't have a lot of time to work on this at the moment. Any time I do have will probably be spent trying to improve the performance of the core functionality so I probably won't be able to implement any other methods any time soon but I would welcome contributions from others in this area.
Feel free to submit a pull request!
